services:
  experiment-scaffold:
    hostname: scaffold
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - ./data:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        Scaffold: 
          partitioning: [Hard, Dirichlet, IID]
          areas: [3, 5, 9]
          seed: { min: 0, max: 5, step: 1 }

#  experiment-fedproxy:
#    hostname: fedproxy
#    build:
#      dockerfile: ./docker/Dockerfile
#      context: .
#    volumes:
#      - ./data:/data
#    environment:
#      DATA_OWNER: 1000:1000
#      LEARNING_HYPERPARAMETERS: |
#        kNNAveraging:
#          agents: [4, 8, 12]
#          neighbors: [1, 3, 5]
#          visible_items: [3, 5]
#          seed: { min: 0, max: 5, step: 1 }